msrv = "1.88"

doc-valid-idents = [
    "..",
    "Aerogram",
    "Nubster",
    "Hexeract",
    "LightShuttle",
    "OpenTelemetry",
    "PostgreSQL",
    "RabbitMQ",
    "GitHub",
    "JMAP",
    "IMAP",
    "SMTP",
    "STARTTLS",
    "SASL",
    "DKIM",
    "DMARC",
    "SPF",
    "ARC",
    "MTA",
    "MUA",
    "MDA",
    "SCIM",
    "OIDC",
    "CloudEvents",
    "JWKS",
    "JWT",
    "S3",
    "MinIO",
    "HTMX",
    "Askama",
    "TLS",
    "MIME",
    "DNSBL",
    "Bayesian",
]
